/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as VehiclesRouteImport } from './routes/Vehicles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as DriverIndexRouteImport } from './routes/driver/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as VehiclesIndexRouteImport } from './routes/Vehicles/index'
import { Route as UserWalletRouteImport } from './routes/user/wallet'
import { Route as UserUserprofileRouteImport } from './routes/user/userprofile'
import { Route as UserTripsRouteImport } from './routes/user/trips'
import { Route as UserSupportRouteImport } from './routes/user/support'
import { Route as UserRidehistoryRouteImport } from './routes/user/ridehistory'
import { Route as UserReviewsRouteImport } from './routes/user/reviews'
import { Route as DriverVehicleRouteImport } from './routes/driver/vehicle'
import { Route as DriverTripsRouteImport } from './routes/driver/trips'
import { Route as DriverSupportRouteImport } from './routes/driver/support'
import { Route as DriverScheduleRouteImport } from './routes/driver/schedule'
import { Route as DriverRequestsRouteImport } from './routes/driver/requests'
import { Route as DriverEarningsRouteImport } from './routes/driver/earnings'
import { Route as DriverDriverprofileRouteImport } from './routes/driver/driverprofile'
import { Route as DashboardVehicleRouteImport } from './routes/dashboard/vehicle'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardTripsRouteImport } from './routes/dashboard/trips'
import { Route as DashboardPromocodeRouteImport } from './routes/dashboard/promocode'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAdminprofileRouteImport } from './routes/dashboard/adminprofile'
import { Route as VehiclesVehiclesIdRouteImport } from './routes/Vehicles/$VehiclesId'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/Vehicles',
  path: '/Vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VehiclesRoute,
} as any)
const UserWalletRoute = UserWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => UserRoute,
} as any)
const UserUserprofileRoute = UserUserprofileRouteImport.update({
  id: '/userprofile',
  path: '/userprofile',
  getParentRoute: () => UserRoute,
} as any)
const UserTripsRoute = UserTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => UserRoute,
} as any)
const UserSupportRoute = UserSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => UserRoute,
} as any)
const UserRidehistoryRoute = UserRidehistoryRouteImport.update({
  id: '/ridehistory',
  path: '/ridehistory',
  getParentRoute: () => UserRoute,
} as any)
const UserReviewsRoute = UserReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => UserRoute,
} as any)
const DriverVehicleRoute = DriverVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => DriverRoute,
} as any)
const DriverTripsRoute = DriverTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DriverRoute,
} as any)
const DriverSupportRoute = DriverSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DriverRoute,
} as any)
const DriverScheduleRoute = DriverScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DriverRoute,
} as any)
const DriverRequestsRoute = DriverRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDriverprofileRoute = DriverDriverprofileRouteImport.update({
  id: '/driverprofile',
  path: '/driverprofile',
  getParentRoute: () => DriverRoute,
} as any)
const DashboardVehicleRoute = DashboardVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTripsRoute = DashboardTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPromocodeRoute = DashboardPromocodeRouteImport.update({
  id: '/promocode',
  path: '/promocode',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminprofileRoute = DashboardAdminprofileRouteImport.update({
  id: '/adminprofile',
  path: '/adminprofile',
  getParentRoute: () => DashboardRoute,
} as any)
const VehiclesVehiclesIdRoute = VehiclesVehiclesIdRouteImport.update({
  id: '/$VehiclesId',
  path: '/$VehiclesId',
  getParentRoute: () => VehiclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Vehicles': typeof VehiclesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/Vehicles/$VehiclesId': typeof VehiclesVehiclesIdRoute
  '/dashboard/adminprofile': typeof DashboardAdminprofileRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/promocode': typeof DashboardPromocodeRoute
  '/dashboard/trips': typeof DashboardTripsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vehicle': typeof DashboardVehicleRoute
  '/driver/driverprofile': typeof DriverDriverprofileRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/schedule': typeof DriverScheduleRoute
  '/driver/support': typeof DriverSupportRoute
  '/driver/trips': typeof DriverTripsRoute
  '/driver/vehicle': typeof DriverVehicleRoute
  '/user/reviews': typeof UserReviewsRoute
  '/user/ridehistory': typeof UserRidehistoryRoute
  '/user/support': typeof UserSupportRoute
  '/user/trips': typeof UserTripsRoute
  '/user/userprofile': typeof UserUserprofileRoute
  '/user/wallet': typeof UserWalletRoute
  '/Vehicles/': typeof VehiclesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/register': typeof RegisterRoute
  '/Vehicles/$VehiclesId': typeof VehiclesVehiclesIdRoute
  '/dashboard/adminprofile': typeof DashboardAdminprofileRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/promocode': typeof DashboardPromocodeRoute
  '/dashboard/trips': typeof DashboardTripsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vehicle': typeof DashboardVehicleRoute
  '/driver/driverprofile': typeof DriverDriverprofileRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/schedule': typeof DriverScheduleRoute
  '/driver/support': typeof DriverSupportRoute
  '/driver/trips': typeof DriverTripsRoute
  '/driver/vehicle': typeof DriverVehicleRoute
  '/user/reviews': typeof UserReviewsRoute
  '/user/ridehistory': typeof UserRidehistoryRoute
  '/user/support': typeof UserSupportRoute
  '/user/trips': typeof UserTripsRoute
  '/user/userprofile': typeof UserUserprofileRoute
  '/user/wallet': typeof UserWalletRoute
  '/Vehicles': typeof VehiclesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/driver': typeof DriverIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Vehicles': typeof VehiclesRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/register': typeof RegisterRoute
  '/user': typeof UserRouteWithChildren
  '/Vehicles/$VehiclesId': typeof VehiclesVehiclesIdRoute
  '/dashboard/adminprofile': typeof DashboardAdminprofileRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/promocode': typeof DashboardPromocodeRoute
  '/dashboard/trips': typeof DashboardTripsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vehicle': typeof DashboardVehicleRoute
  '/driver/driverprofile': typeof DriverDriverprofileRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/driver/schedule': typeof DriverScheduleRoute
  '/driver/support': typeof DriverSupportRoute
  '/driver/trips': typeof DriverTripsRoute
  '/driver/vehicle': typeof DriverVehicleRoute
  '/user/reviews': typeof UserReviewsRoute
  '/user/ridehistory': typeof UserRidehistoryRoute
  '/user/support': typeof UserSupportRoute
  '/user/trips': typeof UserTripsRoute
  '/user/userprofile': typeof UserUserprofileRoute
  '/user/wallet': typeof UserWalletRoute
  '/Vehicles/': typeof VehiclesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Vehicles'
    | '/dashboard'
    | '/driver'
    | '/login'
    | '/payments'
    | '/register'
    | '/user'
    | '/Vehicles/$VehiclesId'
    | '/dashboard/adminprofile'
    | '/dashboard/analytics'
    | '/dashboard/payments'
    | '/dashboard/promocode'
    | '/dashboard/trips'
    | '/dashboard/users'
    | '/dashboard/vehicle'
    | '/driver/driverprofile'
    | '/driver/earnings'
    | '/driver/requests'
    | '/driver/schedule'
    | '/driver/support'
    | '/driver/trips'
    | '/driver/vehicle'
    | '/user/reviews'
    | '/user/ridehistory'
    | '/user/support'
    | '/user/trips'
    | '/user/userprofile'
    | '/user/wallet'
    | '/Vehicles/'
    | '/dashboard/'
    | '/driver/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/payments'
    | '/register'
    | '/Vehicles/$VehiclesId'
    | '/dashboard/adminprofile'
    | '/dashboard/analytics'
    | '/dashboard/payments'
    | '/dashboard/promocode'
    | '/dashboard/trips'
    | '/dashboard/users'
    | '/dashboard/vehicle'
    | '/driver/driverprofile'
    | '/driver/earnings'
    | '/driver/requests'
    | '/driver/schedule'
    | '/driver/support'
    | '/driver/trips'
    | '/driver/vehicle'
    | '/user/reviews'
    | '/user/ridehistory'
    | '/user/support'
    | '/user/trips'
    | '/user/userprofile'
    | '/user/wallet'
    | '/Vehicles'
    | '/dashboard'
    | '/driver'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/Vehicles'
    | '/dashboard'
    | '/driver'
    | '/login'
    | '/payments'
    | '/register'
    | '/user'
    | '/Vehicles/$VehiclesId'
    | '/dashboard/adminprofile'
    | '/dashboard/analytics'
    | '/dashboard/payments'
    | '/dashboard/promocode'
    | '/dashboard/trips'
    | '/dashboard/users'
    | '/dashboard/vehicle'
    | '/driver/driverprofile'
    | '/driver/earnings'
    | '/driver/requests'
    | '/driver/schedule'
    | '/driver/support'
    | '/driver/trips'
    | '/driver/vehicle'
    | '/user/reviews'
    | '/user/ridehistory'
    | '/user/support'
    | '/user/trips'
    | '/user/userprofile'
    | '/user/wallet'
    | '/Vehicles/'
    | '/dashboard/'
    | '/driver/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VehiclesRoute: typeof VehiclesRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  RegisterRoute: typeof RegisterRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Vehicles': {
      id: '/Vehicles'
      path: '/Vehicles'
      fullPath: '/Vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/Vehicles/': {
      id: '/Vehicles/'
      path: '/'
      fullPath: '/Vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/user/wallet': {
      id: '/user/wallet'
      path: '/wallet'
      fullPath: '/user/wallet'
      preLoaderRoute: typeof UserWalletRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/userprofile': {
      id: '/user/userprofile'
      path: '/userprofile'
      fullPath: '/user/userprofile'
      preLoaderRoute: typeof UserUserprofileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/trips': {
      id: '/user/trips'
      path: '/trips'
      fullPath: '/user/trips'
      preLoaderRoute: typeof UserTripsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/support': {
      id: '/user/support'
      path: '/support'
      fullPath: '/user/support'
      preLoaderRoute: typeof UserSupportRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/ridehistory': {
      id: '/user/ridehistory'
      path: '/ridehistory'
      fullPath: '/user/ridehistory'
      preLoaderRoute: typeof UserRidehistoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/reviews': {
      id: '/user/reviews'
      path: '/reviews'
      fullPath: '/user/reviews'
      preLoaderRoute: typeof UserReviewsRouteImport
      parentRoute: typeof UserRoute
    }
    '/driver/vehicle': {
      id: '/driver/vehicle'
      path: '/vehicle'
      fullPath: '/driver/vehicle'
      preLoaderRoute: typeof DriverVehicleRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/trips': {
      id: '/driver/trips'
      path: '/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof DriverTripsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/support': {
      id: '/driver/support'
      path: '/support'
      fullPath: '/driver/support'
      preLoaderRoute: typeof DriverSupportRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/schedule': {
      id: '/driver/schedule'
      path: '/schedule'
      fullPath: '/driver/schedule'
      preLoaderRoute: typeof DriverScheduleRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/requests': {
      id: '/driver/requests'
      path: '/requests'
      fullPath: '/driver/requests'
      preLoaderRoute: typeof DriverRequestsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/driverprofile': {
      id: '/driver/driverprofile'
      path: '/driverprofile'
      fullPath: '/driver/driverprofile'
      preLoaderRoute: typeof DriverDriverprofileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/dashboard/vehicle': {
      id: '/dashboard/vehicle'
      path: '/vehicle'
      fullPath: '/dashboard/vehicle'
      preLoaderRoute: typeof DashboardVehicleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trips': {
      id: '/dashboard/trips'
      path: '/trips'
      fullPath: '/dashboard/trips'
      preLoaderRoute: typeof DashboardTripsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/promocode': {
      id: '/dashboard/promocode'
      path: '/promocode'
      fullPath: '/dashboard/promocode'
      preLoaderRoute: typeof DashboardPromocodeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/adminprofile': {
      id: '/dashboard/adminprofile'
      path: '/adminprofile'
      fullPath: '/dashboard/adminprofile'
      preLoaderRoute: typeof DashboardAdminprofileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/Vehicles/$VehiclesId': {
      id: '/Vehicles/$VehiclesId'
      path: '/$VehiclesId'
      fullPath: '/Vehicles/$VehiclesId'
      preLoaderRoute: typeof VehiclesVehiclesIdRouteImport
      parentRoute: typeof VehiclesRoute
    }
  }
}

interface VehiclesRouteChildren {
  VehiclesVehiclesIdRoute: typeof VehiclesVehiclesIdRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesVehiclesIdRoute: VehiclesVehiclesIdRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminprofileRoute: typeof DashboardAdminprofileRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardPromocodeRoute: typeof DashboardPromocodeRoute
  DashboardTripsRoute: typeof DashboardTripsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardVehicleRoute: typeof DashboardVehicleRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminprofileRoute: DashboardAdminprofileRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardPromocodeRoute: DashboardPromocodeRoute,
  DashboardTripsRoute: DashboardTripsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardVehicleRoute: DashboardVehicleRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DriverRouteChildren {
  DriverDriverprofileRoute: typeof DriverDriverprofileRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverRequestsRoute: typeof DriverRequestsRoute
  DriverScheduleRoute: typeof DriverScheduleRoute
  DriverSupportRoute: typeof DriverSupportRoute
  DriverTripsRoute: typeof DriverTripsRoute
  DriverVehicleRoute: typeof DriverVehicleRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverDriverprofileRoute: DriverDriverprofileRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverRequestsRoute: DriverRequestsRoute,
  DriverScheduleRoute: DriverScheduleRoute,
  DriverSupportRoute: DriverSupportRoute,
  DriverTripsRoute: DriverTripsRoute,
  DriverVehicleRoute: DriverVehicleRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface UserRouteChildren {
  UserReviewsRoute: typeof UserReviewsRoute
  UserRidehistoryRoute: typeof UserRidehistoryRoute
  UserSupportRoute: typeof UserSupportRoute
  UserTripsRoute: typeof UserTripsRoute
  UserUserprofileRoute: typeof UserUserprofileRoute
  UserWalletRoute: typeof UserWalletRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserReviewsRoute: UserReviewsRoute,
  UserRidehistoryRoute: UserRidehistoryRoute,
  UserSupportRoute: UserSupportRoute,
  UserTripsRoute: UserTripsRoute,
  UserUserprofileRoute: UserUserprofileRoute,
  UserWalletRoute: UserWalletRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VehiclesRoute: VehiclesRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  RegisterRoute: RegisterRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
