@url = http://localhost:8000/api

###
GET {{url}}/users/31511632-b063-4e4a-bcad-8a24954d1987


#####
GET {{url}}/payments

#######
POST {{url}}/users
Content-Type: application/json

 {
"firstName": "sarah",
"lastName": "Doe",
"email": "sarahDoe@gmail.com",
"phone": 27123456789,
"password": "passwordsecuure223"
 }


######
POST {{url}}/auth/login
Content-Type: application/json 

{
"email": "JohnDoe@gmail.com",
"password": "passwordsecuure223"
}

##3 rider
valentine@gmail.com
valentine123OMolo

###
PATCH {{url}}/users/69f1bad5-d5d1-4651-905f-31737ad4ca3b
Content-Type: application/json

{
 "phone": "2345678765932"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "chris.anderson1@example.com",
    "password": "SecurePassword1234H"
}