@url = http://localhost:8000/api

###
GET {{url}}/users/31511632-b063-4e4a-bcad-8a24954d1987


####
GET {{url}}/users?search=1234567899



####
GET {{url}}/users/identifier?phone=1234567899




###
GET  {{url}}/users/3980d420-6332-49ca-b1fb-48b27921df63
###
GET {{url}}/driverprofile/c7c2316c-838c-4b57-b9e1-9967d57880d3

####
GET {{url}}/vehicle/2303856d-121f-433d-bedb-706d3d675260


#####
PATCH {{url}}/vehicle/913b8fa2-7d90-4a2a-9cbe-2d662335ff7b
Content-Type: application/json

{
"vehicleImage": "https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg"
}



#####
GET {{url}}/ride


#####
GET {{url}}/payments

#######
POST {{url}}/users
Content-Type: application/json

 {
"firstName": "sarah",
"lastName": "Doe",
"email": "sarahDoe@gmail.com",
"phone": 27123456789,
"password": "passwordsecuure223"
 }


######
POST {{url}}/auth/login
Content-Type: application/json 

{
"email": "JohnDoe@gmail.com",
"password": "passwordsecuure223"
}

##3 rider
valentine@gmail.com
valentine123OMolo

###
PATCH {{url}}/users/69f1bad5-d5d1-4651-905f-31737ad4ca3b
Content-Type: application/json

{
 "phone": "2345678765932"
}

###
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "chris.anderson1@example.com",
    "password": "SecurePassword1234H"
}

"email": "grace@example.com",
  "phone": null,
  "password": "hashedpassword9",


######
GET {{url}}/payments

#####
### Create a payment
POST {{url}}/payments/checkout
Content-Type: application/json

{
  "amount": 50.00,
  "currency": "USD",
  "method": "stripe_checkout",
  "userId": "31511632-b063-4e4a-bcad-8a24954d1987",
  "vehicleId": "09b6e08e-abdc-44f3-b9b8-ccecbacdc611"
}

### Confirm a payment by Stripe Payment Intent ID
POST {{url}}/payments/confirm
Content-Type: application/json

{
  "paymentIntentId": "pi_3RlsABBhAVCGhfBd1QzfleHE"
}

### Get Checkout Session Details
GET {{url}}/payments/session/cs_test_a1gtG4RSn7IZiNeYwTvxgjTTpYKGce9VHB9sfPwGbNAWK3fIC8jiR3VKAK

### Get payment by ID
GET {{url}}/payments

### Update payment by ID
PATCH {{url}}/payments/paymentId
Content-Type: application/json

{
  "status": "completed"
}

### Delete payment by ID
DELETE {{url}}/payments/paymentId


######
GET {{url}}/vehicle

####
PATCH {{url}}/vehicle/ccb796ea-03ef-423b-b9c3-85302f402fb7
Content-Type: application/json

{
  "rentalrate": 67.90
}


####
GET {{url}}/promocode


#####
POST {{url}}/chatbot
Content-Type: application/json

{
  "message": "help"
}


### 1. Send OTP to phone/email for password reset
POST {{url}}/auth/forgot-password
Content-Type: application/json

{
  "emailOrPhone": "+1999888778"
}

### 2. Verify OTP and get password reset token
POST {{url}}/auth/verify-opt
Content-Type: application/json

{
  "phone": "+1999888778",
  "otp": "738708"
}

### 3. Change password if verification is successful
@resetToken= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NzhkYzgyMS1iOTBmLTRkZDktOGYwOS00YjkwN2U3ZGIwMGYiLCJlbWFpbCI6ImdyYWNlLnJvYmluc29uMUBleGFtcGxlLmNvbSIsImlhdCI6MTc1MzE3OTAzOCwiZXhwIjoxNzUzMTc5NjM4fQ.nzkVjSJ8RAN6f0LIykBXE4d5PWRb7EHyU9JyeMKLkgw


#######
POST {{url}}/auth/reset-password
Content-Type: application/json

{
  "token": "{{resetToken}}",
  "newPassword": "new_secure_password"
}
